export const INCREASE_QUANTITY_ONE = 'INCREASE_QUANTITY_ONE';
export const DECREASE_QUANTITY_ONE = 'DECREASE_QUANTITY_ONE';
export const INCREASE_QUANTITY_TWO = 'INCREASE_QUANTITY_TWO';
export const DECREASE_QUANTITY_TWO = 'DECREASE_QUANTITY_TWO';